apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-auth-ecom-sync-svc
  namespace: paris-cl-ecosistema-compra
spec:
  encryptedData:
    .dockerconfigjson: AgALgNwEeFqoX88wtZMqmmqDY5MEnileVQAWnpaXXQ/7ckG3Ln6A8e7NfgiVSM84L43BpvNPJGwPlhWmCCBwFZfxs9HoWIDai518zB9yJmQrOReAXgGZcq2BTjz+M7+lP9PEz/6nM4SfxZgnWs3XKJ2myq30gMDb0avokrGWhX2jDNRed6UUxpXngFRU98xCv/BOZKYk3qY4RulLzTxr3u3+ulqzefkLqKanE3JMXL+860vP83kLBxiuHTjIwBVGnGgBF6gMqYESzOWZHyYAk3qkBmkDbzHXapeXpugjvLAVolG3Uwa0IRco4tMDc98pdnsVnETVSpNP5Eq8io+vQDtedugSb7j5Rr1vHcr8nPAwXM95nhIS30FMbrzFYwLwWFyur/8oeAhDpIeZjEazbPxq3vUp9kBzXVLkpa4n8KD2680UWi/IQQPTKjV0FL14NOjLP81G6lzk8PsM/isRrEP04LwBnPfWUVGmN9Hp87VTbTtWah6QsV2q/JaptFrS9ouEZU1wT4hgzZH54Km99GbYTbADyV/EQ6SSqSOOPOl4Ymls7IxQ803PPPbxIu8s/HUn3ObDMvvF11vQ0ZyfT6qEkoypE/LSyPzL0J+9QDgVwVqW0WKOxH2nfqksbzCIA/OyfXKy7sRUoZtchdnsSMUNl2/zhuVfEbJIlehB/6Il9nSeWXoqbNCsYdEsHXboHWLKCbOn/IBqfih9AlWuS9LV97p1tS5CFnr4H0caiV6BmteCXVSgXAwGc2mUSzpEH/nuQDDK9F2aYsKT/kHeZ1pJqsih8i3U5Pvc3aWS5etgwJQN8aTP1nCx+Xap0cfg2p37XiHO6P+b37oeWr4fPwR6nFocVlgYillm6hoHmx5mV7LMwtTxB0z9lC9hCSvtkVcA+b9jRrB9+svX7Q51LCsiWR5bLKxOUh4=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-auth-ecom-sync-svc
      namespace: paris-cl-ecosistema-compra
    type: kubernetes.io/dockerconfigjson

