apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-auth-ecom-sync-svc
  namespace: paris-cl-ecosistema-compra
spec:
  encryptedData:
    .dockerconfigjson: AgAeT2To/QysBMcBQ84msbp4Lc0JmuLiWNB0mXGo7vpY0jcMNRmGHAln4rASnC7WIYXdC3GlAfx8SF1y6mRNTaJs/inz7/Fz1igybzNXxxYm2QIqDe6duwg/rPzhYustDJdOKPCySa/3s+zCU3dP+g/3rXzdIYQo2kQQf2CRwtR9zkNPqpQ2G+sHmHMiHRw/7AEfXMH/rjE4DBkfTsCIMZrUYkV/I/JlBqjXU8O1e3EqUT/G/dodgQB7DZ+kOk4rnBsIQk+DeJGqjxVktQjch6Hrx4ZxsOB3WMPcKQOmB2dtkdH30RmDYqX4N3s0gBZXNHQCFAfH9U6F//izv+N5i/dLVo3w8/B+I+TtisgmzioqGG2N9c3MJtijCqHdz58I8WiBP7AI2D8DG9yudcyIi9kA2XjnV4aILQSEz0KSM8lxC+3p7LOu1OzNtrZndv3W05L1F8LaMIOrEBRI0BH67qpgP54yIomf3ykkPSewdya2td2w3/j5vjOg5aIQztqH1sc6nnn3t1MjURwffa63spr/NTUH2jt5Bhc4NcT2AqU9jtFAhZQ2sg9MC/VMLBDvU4eciDHJOk058HLNBdtydcTusleCFlDYDhCj5mL1EkW9q+IoQkpsjndR+5g6QXp0pLUqbCDS2i6Qqu9cKRzzbD+SnR2mTXcz4ip5CFVYPyBTgBdLdOJMg6d4yOrdtG99xvW5hUU7P0bUEOHRLNkSHowmfOtbfP1lp/VTlcN4p8emat2rAecG89YQFS6akkeWKxcfwQEoRDrDDaZaR///mNReTwppqCx8wJrb6+Vok4pv8Pl5EwDhD14a4KFGMYwYthBQVi+hA4Ys4vZatpWsEC9lbZH8oukjJ++x0qbjO69DtNnqyOrmLftcmulLhOxmFJsg9uR2mDyI+KzhwCivDqiMFGUbqdqSfNQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-auth-ecom-sync-svc
      namespace: paris-cl-ecosistema-compra
    type: kubernetes.io/dockerconfigjson

