# kustomize build --load_restrictor none
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base
- docker-pull-secrets.yaml
- ecom-sync-svc-secret.yaml

  # app.paristech.io/version: "x.x.xxx"
commonLabels:
  app.paristech.io/cluster-name: green
  app.paristech.io/component: ecom-sync
  app.paristech.io/environment: production
  app.paristech.io/instance: ecom-sync-svc
  app.paristech.io/managed-by: argocd
  app.paristech.io/name: ecom-sync
  app.paristech.io/part-of: paris-cl-ecosistema-compra

generatorOptions:
  disableNameSuffixHash: true

commonAnnotations:
  team.paristech.io/developer: gonzalo-leyton
  team.paristech.io/owner: gonzalo-leyton
  team.paristech.io/product-name: paris-cl-ecosistema-compra
  team.paristech.io/source-repo-url: https://gitlab.com/cencosud-ds/ordenes-y-entrega/planning/ecom-sync-svc

configMapGenerator:
- behavior: merge
  envs:
  - ../config.properties
  name: ecom-sync-svc-configmap

  # Añadimos esta seccion que sirve para realizar pequeñas modificaciones a manifiestos específicos.
  # En este caso realizaremos modificaciones a las anotaciones que nos sirven para balancear por DNS y cambios de host.
patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 3
  target:
    group: apps
    kind: Deployment
    name: ecom-sync-svc-deployment
    version: v1
- patch: |-
    - op: replace
      path: /spec/minReplicas
      value: 3
    - op: replace
      path: /spec/maxReplicas
      value: 6
  target:
    group: autoscaling
    kind: HorizontalPodAutoscaler
    name: ecom-sync-svc-hpa
    version: v2beta2
- patch: |-
    - op: replace
      path: /data/NEW_RELIC_APP_NAME
      value: "green-ecom-sync-svc Production"
  target:
    kind: ConfigMap
    name: ecom-sync-svc-configmap
    version: v1
images:
- name: registry.gitlab.com/cencosud-ds/ordenes-y-entrega/planning/ecom-sync-svc
  newTag: master-255-1964e587
