apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitlab-auth-ecom-sync-svc
  namespace: paris-cl-ecosistema-compra
spec:
  encryptedData:
    .dockerconfigjson: AgCJ7mfDmEHNsoJVu8AnK1FVdQNQFdDGc3zcKo6ePNZEhgV+cSO6j1pvqR4iTWikTARysdYhpkORowzsqAx2SpABOjk/BdcqMvWOu/5to4a8ogQpo1FOeFc8cDmhyBxNDiA8G72NEOT0xV/WwuQlC8F7MgdjjzZSc3jScNBxKpiUkkjeTYVYYzh6VQFJXJRzzWOChYm/N9Jjmfo+DZY1KBxgTHqhU5dF/SPrEz9Vj1mo56KIsSQkXsrMgVAPQGAtuztLlzIZRjR7319BVnDl6XrAmOJsDgbnrvBIT0Zh04pj4KuSz3zdMHl1aRIxVO+ZEiqYQVSsoVABViyUACxep3/S5NmpMnY8yV2X71vxpyxUhrmIOUDlpSKyzKlDIqDkm3jZ5rvpKc0KAFGXepxtae5fadgGhMwsUbeeGrn0czxjyyQ4FYHEf3CgZ/dpZuOlw+W/JMEebIp2S3jnvIRhy7LNZoa7lj4/fxhi2T0SrOnRHGo1sgs8iHdd0rSrKHJ5mt0NXrCqAR0MHGCaDwYoMgcRHWwziN99DtUp1H+Hfx2W/G2lbm9jyrhGNlLFitUm7cX0O4pZaD9gkM6I4uw275q0LaRmirOQxbPcDA3gQgTWoA/7VR0bsVjoUVhG/mWg4mX96t6sqWAopE9OFo6HigrtP4GmFIGhbvLFWprmpujT/Wnag53nDw2OC9pqmMjMUdwa1bO0mE6B2jDapkjsVL8SYA4EhgTNQ9+hwJ5maxkOwOyybOyQHijoCfpHTESoaEpcrdpVhYo2y2oXXZBRJ/baJCPoos4DNrxDRIN/v1b7yOiLpdpnTtW71bKMuRSnZomWNU31nSftWuB7bxeuz2Mj3ltiNKow4xWxLp6mx4RjRSCUXlL75aGA5MEykY2LyaTX8U1vB3MsfFE/NZyH9UBBQC5aoS90pHQ=
  template:
    metadata:
      creationTimestamp: null
      name: gitlab-auth-ecom-sync-svc
      namespace: paris-cl-ecosistema-compra
    type: kubernetes.io/dockerconfigjson

