apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: <SERVICE_NAME>-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <SERVICE_NAME>-deployment
  minReplicas: <REPLICA_NUMBER>
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: 80
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
