export enum FeatureType {
  StyleList = 'StyleList',
  StyleEdit = 'StyleEdit',
  StyleCreate = 'StyleCreate',
  StyleDelete = 'StyleDelete',
  PurchaseCreate = 'PurchaseCreate',
  PurchaseList = 'PurchaseList',
  PurchaseStyleMod = 'PurchaseStyleMod',
  PurchaseApprovement = 'PurchaseApprovement',
  PurchaseReport = 'PurchaseReport',
  OCReport = 'OCReport',
  PIReport = 'PIReport',
  PurchaseOrderReport = 'PurchaseOrderReport',
  Mantainers = 'Mantainers',
  UserCreate = 'UserCreate',
  UserList = 'UserList',
  UserEdit = 'UserEdit',
  UserDelete = 'UserDelete',
}
