apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ecom-sync-svc
    area: txd
    name: ecom-sync-svc
    version: "1"
  name: ecom-sync-svc-deployment
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 3
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: ecom-sync-svc
      area: txd
      name: ecom-sync-svc
      version: "1"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ecom-sync-svc
        area: txd
        name: ecom-sync-svc
        version: "1"
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              topologyKey: kubernetes.io/hostname
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: failure-domain.beta.kubernetes.io/zone
      containers:
      - envFrom:
        - secretRef:
            name: ecom-sync-svc-secrets
        - configMapRef:
            name: ecom-sync-svc-configmap
        image: registry.gitlab.com/cencosud-ds/ordenes-y-entrega/planning/ecom-sync-svc:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /ecom/sync/api/v1/health
            port: 5005
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        name: ecom-sync-svc
        ports:
        - containerPort: 5005
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ecom/sync/api/v1/health
            port: 5005
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1536Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gitlab-auth-ecom-sync-svc
      nodeSelector:
        node.kubernetes.io/role: "user"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: high
status: {}
