apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: <SERVICE_NAME>-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: <SERVICE_NAME>-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 81
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 81