apiVersion: kustomize.config.k8s.io/v1beta1 # apiVersion de kustomize
kind: Kustomization # Especificamos que es una kustomization
namespace: paris-cl-ecosistema-compra # Namespace de kubernetes de destino
                        # Nota: El namespace no está definido en los manifiestos. Se añade automático

images: # La imagen de nuestro contenedor tiene que coincidir con el del manifiest, luego en el pipeline se cambia de acuerdo con nuestro build.
- name: registry.gitlab.com/cencosud-ds/ordenes-y-entrega/planning/ecom-sync-svc:latest

resources: # Especificamos los recursos/manifiestos que se verán involucrados en nuestra configuración.
  - deployment.yaml
  - service.yaml
  - hpa.yaml